version: '2'
services:
  laravel:
    build:
      context: ./docker
      dockerfile: docker-image-dev.txt
    ports:
      - 2007:80
      - 2008:443
    env_file: .env
    links:
      - database
    volumes:
      - .:/var/www/laravel

  database:
    image: postgres:9.6
    ports:
      - 5999:5432
    env_file: .env
    environment:
      LC_ALL: C.UTF-8
    volumes:
      - ./storage/backups:/var/backups
